"""Add insurance claims and split billing

Revision ID: 136561198eb5
Revises: ddaa26da84a2
Create Date: 2026-07-02 19:42:11.551587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '136561198eb5'
down_revision: Union[str, None] = 'ddaa26da84a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('claim_status', sa.Enum('PENDING', 'APPROVED', 'SETTLED', name='claimstatusenum', native_enum=False, length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_id'), 'insurance_claims', ['id'], unique=False)
    op.add_column('billings', sa.Column('patient_payable', sa.Float(), nullable=True))
    op.add_column('billings', sa.Column('insurance_payable', sa.Float(), nullable=True))
    op.alter_column('billings', 'payment_mode',
               existing_type=postgresql.ENUM('CASH', 'UPI', 'CARD', name='paymentmodeenum'),
               type_=sa.Enum('CASH', 'UPI', 'CARD', name='paymentmodeenum', native_enum=False, length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billings', 'payment_mode',
               existing_type=sa.Enum('CASH', 'UPI', 'CARD', name='paymentmodeenum', native_enum=False, length=50),
               type_=postgresql.ENUM('CASH', 'UPI', 'CARD', name='paymentmodeenum'),
               existing_nullable=True)
    op.drop_column('billings', 'insurance_payable')
    op.drop_column('billings', 'patient_payable')
    op.drop_index(op.f('ix_insurance_claims_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    # ### end Alembic commands ###
