"""Add reminder sent flag

Revision ID: 1800f6382885
Revises: 6388f8066250
Create Date: 2026-07-02 19:55:10.191352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1800f6382885'
down_revision: Union[str, None] = '6388f8066250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'reminder_sent')
    # ### end Alembic commands ###
