"""Add triage level

Revision ID: 38cb75e115c7
Revises: 7b5d2756ae06
Create Date: 2026-07-02 16:34:34.469559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cb75e115c7'
down_revision: Union[str, None] = '7b5d2756ae06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('triage_level', sa.String(50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'triage_level')
    # ### end Alembic commands ###
