"""Add follow up date

Revision ID: 6388f8066250
Revises: daf9409acea4
Create Date: 2026-07-02 19:53:52.260349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6388f8066250'
down_revision: Union[str, None] = 'daf9409acea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'follow_up_date')
    # ### end Alembic commands ###
