"""add_email_and_address_to_patients

Revision ID: 7b5d2756ae06
Revises: da0fbeb30bb0
Create Date: 2026-06-19 14:34:21.349145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5d2756ae06'
down_revision: Union[str, None] = 'da0fbeb30bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###
