from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.visit import Visit, TriageLevel
from app.models.patient import Patient
from app.models.user import User, RoleEnum
from app.schemas.schemas import VisitCreate, VisitResponse
from app.routes.auth_routes import get_current_user
from app.utils.notifications import send_sms_background

router = APIRouter(prefix="/visits", tags=["visits"])

@router.post("/", response_model=VisitResponse)
def create_visit(visit: VisitCreate, background_tasks: BackgroundTasks, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    patient = db.query(Patient).filter(Patient.id == visit.patient_id).first()
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")
        
    pending_visit = db.query(Visit).filter(Visit.patient_id == visit.patient_id, Visit.doctor_id == None).first()
    
    if pending_visit:
        pending_visit.doctor_id = current_user.id
        pending_visit.bp = visit.bp
        pending_visit.weight = visit.weight
        pending_visit.pulse = visit.pulse
        if current_user.role == RoleEnum.DOCTOR:
            pending_visit.medicines = visit.medicines
            pending_visit.notes = visit.notes
            pending_visit.follow_up_date = visit.follow_up_date
            
        db.commit()
        db.refresh(pending_visit)
        
        # Trigger Notifications if Doctor just added medicines
        if current_user.role == RoleEnum.DOCTOR and visit.medicines and patient.mobile:
            msg = f"Hello {patient.name}, your prescription has been generated by Dr. {current_user.username}."
            if visit.follow_up_date:
                msg += f" Please follow up on {visit.follow_up_date.strftime('%Y-%m-%d')}."
            background_tasks.add_task(send_sms_background, patient.mobile, msg)
            
        return pending_visit
    else:
        new_visit = Visit(
            patient_id=visit.patient_id,
            doctor_id=current_user.id,
            bp=visit.bp,
            weight=visit.weight,
            pulse=visit.pulse,
            medicines=visit.medicines,
            notes=visit.notes,
            triage_level=TriageLevel.GREEN
        )
        db.add(new_visit)
        db.commit()
        db.refresh(new_visit)
        return new_visit

@router.get("/patient/{patient_id}", response_model=list[VisitResponse])
def get_patient_visits(patient_id: int, db: Session = Depends(get_db)):
    visits = db.query(Visit).filter(Visit.patient_id == patient_id).all()
    return visits
